version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unconvert

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
  skip-dirs:
    - vendor

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  gofmt:
    simplify: true
    tabwidth: 4

  goimports:
    local-prefixes: "github.com/recipemarkdown/app/backend"
